{
  "Entries": [
    {
      "RequestUri": "https://api.loganalytics.io/v1/workspaces/32d1e136-gg81-4b0a-b647-260cdc471f68/query",
      "RequestMethod": "POST",
      "RequestHeaders": {
        "Accept": "application/json",
        "Accept-Encoding": "gzip",
        "Authorization": "Sanitized",
        "Content-Length": "47",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-go-azlogs/v0.1.0 (go1.19.3; linux)"
      },
      "RequestBody": {
        "query": "not a valid query",
        "timespan": "PT2H"
      },
      "StatusCode": 400,
      "ResponseHeaders": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Expose-Headers": "Retry-After,Age,WWW-Authenticate,x-resource-identities,x-ms-status-location",
        "Connection": "keep-alive",
        "Content-Length": "355",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Tue, 05 Mar 2024 23:32:29 GMT",
        "Strict-Transport-Security": "max-age=15724800; includeSubDomains",
        "Vary": "Accept-Encoding",
        "Via": "1.1 draft-oms-7bfc9d5446-bstdj",
        "X-Content-Type-Options": "nosniff"
      },
      "ResponseBody": {
        "error": {
          "message": "The request had some invalid properties",
          "code": "BadArgumentError",
          "correlationId": "139442f3-5e3b-4ae0-b1f5-efd0259b130f",
          "innererror": {
            "code": "SyntaxError",
            "message": "A recognition error occurred in the query.",
            "innererror": {
              "code": "SYN0002",
              "message": "Query could not be parsed at \u0027a\u0027 on line [1,5]",
              "line": 1,
              "pos": 5,
              "token": "a"
            }
          }
        }
      }
    }
  ],
  "Variables": {}
}
