{
  "Entries": [
    {
      "RequestUri": "https://Sanitized.azure.com/providers/Informatica.DataManagement/operations?api-version=2024-05-08",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Accept": "application/json",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
        "User-Agent": "azsdk-python-mgmt-informaticadatamanagement/1.0.0b1 Python/3.10.11 (Windows-10-10.0.22631-SP0)"
      },
      "RequestBody": null,
      "StatusCode": 404,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "250",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Thu, 23 May 2024 09:19:09 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "X-Cache": "CONFIG_NOCACHE",
        "X-Content-Type-Options": "nosniff",
        "x-ms-correlation-request-id": "fccf854d-11fe-4fbd-8f4e-516013407392",
        "x-ms-failure-cause": "gateway",
        "x-ms-ratelimit-remaining-tenant-reads": "11999",
        "x-ms-routing-request-id": "JAPANWEST:20240523T091910Z:fccf854d-11fe-4fbd-8f4e-516013407392",
        "X-MSEdge-Ref": "Ref A: DBDBDE4C3159496EB8AB993E6D8E88B5 Ref B: TYO201100116051 Ref C: 2024-05-23T09:19:10Z"
      },
      "ResponseBody": {
        "error": {
          "code": "InvalidResourceType",
          "message": "The resource type 'operations' could not be found in the namespace 'Informatica.DataManagement' for api version '2024-05-08'. The supported api-versions are '2023-03-01-preview,2023-08-20-preview'."
        }
      }
    }
  ],
  "Variables": {}
}
