{
  "Entries": [
    {
      "RequestUri": "https://vaultname.vault.azure.net/certificates/cert-that-does-not-exist/?api-version=7.4",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Accept": "application/json",
        "Accept-Encoding": "gzip, deflate",
        "User-Agent": "azsdk-python-keyvault-certificates/4.7.1 Python/3.10.0 (Windows-10-10.0.22621-SP0)"
      },
      "RequestBody": null,
      "StatusCode": 404,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "336",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Thu, 18 May 2023 00:46:27 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=172.92.159.124;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus",
        "x-ms-keyvault-service-version": "1.9.804.1"
      },
      "ResponseBody": {
        "error": {
          "code": "CertificateNotFound",
          "message": "A certificate with (name/id) cert-that-does-not-exist was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182"
        }
      }
    }
  ],
  "Variables": {}
}
